# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concatenate <- function(x, y) {
    .Call('_RcppFun_concatenate', PACKAGE = 'RcppFun', x, y)
}

#' Compare columns and vector
#'
#' Matches columns of a matrix against a vector.
#' @param x nxm character matrix
#' @param y character vector of length n
#' @param s string denoting the blanks in matrix and vector that
#' will not be used for comparison
#' @return Numeric matrix with a relative (regarding to the blank string)
#' best match for the column
#' in column one and a relative best match for the vector in column 2.
#' @export
compareMV <- function(x, y, s = "-") {
    .Call('_RcppFun_compareMV', PACKAGE = 'RcppFun', x, y, s)
}

#' Extend data by degree 2
#'
#' All interaction terms (including quadratics) will be computed.
#'
#' @param x numeric nxm matrix with variables as columns
#' @param exp exponent (see polynomial kernel)
#' @param base basis (see polynomial kernal)
#' @param fac factor (see polynomial kernel)
#' @return extended matrix with ((n-1)*n)/2 + 2n columns
#' @export
extendData <- function(x, exp = 0.5, base = 2, fac = 1) {
    .Call('_RcppFun_extendData', PACKAGE = 'RcppFun', x, exp, base, fac)
}

#' Matrix multiplication
#'
#' @param A numeric nxm matrix
#' @param B numeric mxl matrix
#' @return numeric nxl matrix
#' @export
eigenMapMatMult <- function(A, B) {
    .Call('_RcppFun_eigenMapMatMult', PACKAGE = 'RcppFun', A, B)
}

#' Transitive closure
#'
#' @param x numeric nxn matrix (should be binary)
#' @return transitive closure of x
#' @export
transClose_W <- function(x) {
    .Call('_RcppFun_transClose_W', PACKAGE = 'RcppFun', x)
}

#' Transitive closure after deletion
#'
#' @param x numeric nxn matrix (should be binary) that was transitively closed before an edge deletion
#' @param u row index of deleted edge
#' @param v column index of deleted edge
#' @return transitive closure of x
#' @export
transClose_Del <- function(x, u, v) {
    .Call('_RcppFun_transClose_Del', PACKAGE = 'RcppFun', x, u, v)
}

#' Transitive closure after addition
#'
#' @param x numeric nxn matrix (should be binary) that was transitively closed before an edge addition
#' @param u row index of added edge
#' @param v column index of added edge
#' @return transitive closure of x
#' @export
transClose_Ins <- function(x, u, v) {
    .Call('_RcppFun_transClose_Ins', PACKAGE = 'RcppFun', x, u, v)
}

#' Transitive closure after deletion
#'
#' @param x numeric nxm matrix
#' @return numeric vector of length n with the maximum for each row
#' @export
maxCol_row <- function(x) {
    .Call('_RcppFun_maxCol_row', PACKAGE = 'RcppFun', x)
}

