# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
concatenate <- function(x, y) {
    .Call(`_RcppFun_concatenate`, x, y)
}

#' Extend data by degree 2
#'
#' All interaction terms (including quadratic) will be computed.
#'
#' @param x numeric nxm matrix with variables as columns
#' @param exp exponent (see polynomial kernel)
#' @param base base (see polynomial kernal)
#' @param coef0 factor (see polynomial kernel)
#' @return extended matrix with ((n-1)*n)/2 + 2n + 1 columns
#' @export
extendData <- function(x, exp = 0.5, base = 2, coef0 = 1) {
    .Call(`_RcppFun_extendData`, x, exp, base, coef0)
}

#' Compare columns and vector
#'
#' Matches columns of a matrix against a vector.
#' @param x nxm character matrix
#' @param y character vector of length n
#' @param s string denoting the gaps in matrix and vector that
#' will not be used for comparison
#' @return Numeric matrix with a relative (regarding to the gap string)
#' best match for the column
#' in column one and a relative best match for the vector in column 2.
#' @export
compareMV <- function(x, y, s = "-") {
    .Call(`_RcppFun_compareMV`, x, y, s)
}

#' Matrix multiplication
#'
#' @param A numeric nxm matrix
#' @param B numeric mxl matrix
#' @return numeric nxl matrix
#' @export
eigenMapMatMult <- function(A, B) {
    .Call(`_RcppFun_eigenMapMatMult`, A, B)
}

#' Transitive closure
#'
#' @param x numeric nxn matrix (should be binary)
#' @return transitive closure of x
#' @export
transClose_W <- function(x) {
    .Call(`_RcppFun_transClose_W`, x)
}

#' Transitive closure after deletion
#'
#' @param x numeric nxn matrix (should be binary) that was transitively closed before an edge deletion
#' @param u row index of deleted edge
#' @param v column index of deleted edge
#' @return transitive closure of x
#' @export
transClose_Del <- function(x, u, v) {
    .Call(`_RcppFun_transClose_Del`, x, u, v)
}

#' Transitive closure after addition
#'
#' @param x numeric nxn matrix (should be binary) that was transitively closed before an edge addition
#' @param u row index of added edge
#' @param v column index of added edge
#' @return transitive closure of x
#' @export
transClose_Ins <- function(x, u, v) {
    .Call(`_RcppFun_transClose_Ins`, x, u, v)
}

#' Transitive closure after deletion
#'
#' @param x numeric nxm matrix
#' @return numeric vector of length n with the maximum for each row
#' @export
maxCol_row <- function(x) {
    .Call(`_RcppFun_maxCol_row`, x)
}

